#!/bin/bash
# =============================================================================
# MinIO Setup Script for InkDapper VPS
# Run this ONCE on the VPS to install and configure MinIO.
#
# Usage:
#   chmod +x scripts/setup-vps-minio.sh
#   sudo bash scripts/setup-vps-minio.sh
#
# What this does:
#   1. Downloads the MinIO binary
#   2. Creates a dedicated 'minio' system user
#   3. Creates the data directory
#   4. Creates /etc/default/minio with strong credentials
#   5. Creates and enables a systemd service
#   6. Starts MinIO
# =============================================================================

set -e

# ── CONFIG — change these before running ──────────────────────────────────
MINIO_DATA_DIR="/data/minio"
MINIO_ACCESS_KEY="inkdapper_minio_admin"          # change to something strong
MINIO_SECRET_KEY="$(openssl rand -hex 32)"        # auto-generates a strong key
MINIO_BUCKET="inkdapper"
# ──────────────────────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Must run as root
[ "$(id -u)" -ne 0 ] && error "Run this script with sudo."

info "Installing MinIO..."

# ── 1. Download MinIO binary ──────────────────────────────────────────────
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
  MINIO_URL="https://dl.min.io/server/minio/release/linux-amd64/minio"
elif [ "$ARCH" = "aarch64" ]; then
  MINIO_URL="https://dl.min.io/server/minio/release/linux-arm64/minio"
else
  error "Unsupported architecture: $ARCH"
fi

wget -q --show-progress -O /usr/local/bin/minio "$MINIO_URL"
chmod +x /usr/local/bin/minio
info "MinIO binary installed at /usr/local/bin/minio"
/usr/local/bin/minio --version

# ── 2. Create system user ─────────────────────────────────────────────────
if ! id -u minio-user &>/dev/null; then
  useradd -r -s /sbin/nologin minio-user
  info "Created system user: minio-user"
else
  info "System user minio-user already exists"
fi

# ── 3. Create data directory ──────────────────────────────────────────────
mkdir -p "$MINIO_DATA_DIR"
chown -R minio-user:minio-user "$MINIO_DATA_DIR"
info "Data directory: $MINIO_DATA_DIR"

# ── 4. Create environment config ──────────────────────────────────────────
cat > /etc/default/minio <<EOF
# MinIO Environment Config
# Generated by setup-vps-minio.sh — edit as needed

MINIO_VOLUMES="$MINIO_DATA_DIR"

# API port 9000, Console port 9001 — both bound to localhost only
MINIO_OPTS="--address 127.0.0.1:9000 --console-address 127.0.0.1:9001"

MINIO_ROOT_USER="$MINIO_ACCESS_KEY"
MINIO_ROOT_PASSWORD="$MINIO_SECRET_KEY"
EOF
chmod 600 /etc/default/minio
info "Environment config written to /etc/default/minio"

# ── 5. Create systemd service ─────────────────────────────────────────────
cat > /etc/systemd/system/minio.service <<'EOF'
[Unit]
Description=MinIO Object Storage
Documentation=https://min.io/docs/minio/linux/index.html
Wants=network-online.target
After=network-online.target
AssertFileIsExecutable=/usr/local/bin/minio

[Service]
Type=simple
WorkingDirectory=/usr/local

User=minio-user
Group=minio-user

EnvironmentFile=/etc/default/minio
ExecStartPre=/bin/bash -c "if [ -z \"${MINIO_VOLUMES}\" ]; then echo \"Variable MINIO_VOLUMES not set\"; exit 1; fi"
ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES

# Let systemd restart MinIO on failure
Restart=always
RestartSec=5

# Limit process to sane resource usage
LimitNOFILE=65536
TasksMax=infinity
TimeoutStopSec=60
SendSIGKILL=no

# Disable memory swapping
MemorySwapMax=0

# Do not inherit environment from calling process
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable minio
systemctl start minio
info "MinIO service started and enabled"

# ── 6. Verify it's running ────────────────────────────────────────────────
sleep 3
if systemctl is-active --quiet minio; then
  info "MinIO is running!"
  echo ""
  echo -e "${GREEN}================================================================${NC}"
  echo -e "${GREEN} MinIO installed successfully!${NC}"
  echo -e "${GREEN}================================================================${NC}"
  echo ""
  echo "  API endpoint : http://127.0.0.1:9000  (proxied as storage.inkdapper.com)"
  echo "  Console      : http://127.0.0.1:9001  (SSH tunnel only)"
  echo ""
  echo "  Access key   : $MINIO_ACCESS_KEY"
  echo "  Secret key   : $MINIO_SECRET_KEY"
  echo ""
  echo -e "${YELLOW}  IMPORTANT: Copy the secret key above into your backend .env file!${NC}"
  echo "  Set these in /var/www/inkdapper-dev/backend/.env:"
  echo ""
  echo "    MINIO_ENDPOINT=127.0.0.1"
  echo "    MINIO_PORT=9000"
  echo "    MINIO_USE_SSL=false"
  echo "    MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY"
  echo "    MINIO_SECRET_KEY=$MINIO_SECRET_KEY"
  echo "    MINIO_BUCKET_NAME=$MINIO_BUCKET"
  echo "    MINIO_REGION=us-east-1"
  echo "    MINIO_PUBLIC_URL=https://storage.inkdapper.com"
  echo ""
  echo "  To access MinIO Console via SSH tunnel:"
  echo "    ssh -L 9001:localhost:9001 user@your-vps-ip"
  echo "    Then open: http://localhost:9001"
  echo ""
else
  error "MinIO failed to start. Check logs: sudo journalctl -u minio -n 50"
fi
